### PR TITLE
fixes #72 

### LINKED ISSUE #72: java.io.IOException: Attempted read from closed stream.  MS changed the Teams response
I found the issue in logsteamcity-server.log on the build server. 
java.io.IOException: Attempted read from closed stream.
at msteamsnotifications.MsTeamsNotificationImpl.postViaWebHook(MsTeamsNotificationImpl.java:184)

Microsoft made a change that broke things for many people. 
The change in the Webhook is documented here: https://github.com/MicrosoftDocs/msteams-docs/issues/7830

### PR DESCRIPTION
**Pull request by Eric-Maddox**
fix  IOException after MS changed response
use correct ContentType to avoid 400 error
Includes unit test.

### CODE REVIEW

**Comment by spyder007** [comment]
@Eric-Maddox I will gladly create a release for this, but the pipeline is not currently building, can you take a look?

**Comment by Eric-Maddox** [comment]
I don't know why the build is failing. If I create an empty folder, and do a `git clone` from my fork, then type `mvn` it builds successfully. 
The method it's complaining about is InputStream.nullInputStream(). Documentation says it's been their "Since 11"
https://download.java.net/java/early_access/panama/docs/api/java.base/java/io/InputStream.html#nullInputStream()

**Comment by olamartensson** [comment]
Hi! We are using this plugin and are now seeing the exact same issue on our TeamCity instance.

Could the broken build be fixed by bumping the Java version in the GitHub workflow config? It seems to currently be configured for Java 8 ([`java-version: 1.8`](https://github.com/spyder007/teamcity-msteams-notifier/blob/bc70bfeacacfed66cc63697cdc04a6b86e44eb8a/.github/workflows/build.yml#L25)) and the `nullInputStream()` method was added in Java 11, as you wrote.

**Comment by spyder007** [comment]
@Eric-Maddox Can you please sync with the latest commit on `master`?  I moved the build to JDK 11, which hopefully fixes this build error.

**Review by spyder007 — APPROVED** [review]
lgtm

**Comment by spyder007** [comment]
@Eric-Maddox / @olamartensson -> This is merged and I created a new release (2.13.0).

**Comment by olamartensson** [comment]
Thanks a lot! I have now tested the new release on our TeamCity instance and Teams notifications are working again 👍

**Pull request merged**
